global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["recommender:8000"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis_exporter:9121"]
